from typing import Protocol


class AuthService(Protocol):
    def __init__(self, secret: str, algorithm: str) -> None: ...

    def create_token_pair(self, account_id: int) -> dict: ...

    def refresh_token_pair(self, refresh_token: str) -> dict: ...

    def get_payload(self, access_token: str) -> dict: ...
