"""Абстракция репозитория"""

from typing import Optional, Protocol

from .entities import Account


class AccountRepository(Protocol):
    def get_by_id(self, id: int) -> Optional[Account]: ...
    def get_by_email(self, email: str) -> Optional[Account]: ...
    def save(self, account: Account) -> Account: ...


class PasswordService(Protocol):
    @staticmethod
    def hash_password(password: str) -> str: ...
    @staticmethod
    def check_password(password: str, hashed_password: str) -> bool: ...


class AuthService(Protocol):
    def __init__(self, secret: str, algorithm: str) -> None: ...

    def create_token_pair(self, account_id: int) -> dict: ...

    def refresh_token_pair(self, refresh_token: str) -> dict: ...

    def get_payload(self, access_token: str) -> dict: ...


class MailSender(Protocol):
    def send_code(self, code: int, to_email: str) -> None: ...


class CacheService(Protocol):
    def post_confirmation_code(self, account: Account, code: int) -> None: ...

    def get_info_by_email(self, email: str) -> dict | None: ...

    def delete_by_email(self, email: str) -> bool: ...
