"""Абстракция репозитория"""

from typing import Protocol

from account.domain.entities import Account


class AccountRepository(Protocol):
    def get_by_id(self, account_id: int) -> Account | None: ...
    def get_by_email(self, email: str) -> Account | None: ...
    def get_by_username(self, username: str) -> Account | None: ...
    def save(self, account: Account) -> Account: ...
